mindmap
    root((Dickinson <br> College))
    
        ((Academic <br> Buildings))
        ::icon(fa fa-building)
            Rector Science <br> Building
                **Tome Hall**
                The other ones
            Bosler
            Althouse
            East College
            Denny

        ((Residence <br> Halls))
        ::icon(fa fa-house)
            Morgan
            High Street
            Drayer
            Kisner-Woodward
            Adams
            Armstrong
            Atwater
            Baird
            Buchanan
            David-Wilson
            Malcolm
            Witwer

        ((Facilities <br>ㅤㅤㅤㅤㅤㅤ))
            ::icon(fa fa-mug-hot)
            HUB
            Kline Center
            Old West
           