sankey-beta

%% studio,title, total copies sold (millions)
Nintendo, Mario Kart 8 Deluxe, 55.46
Nintendo, Animal Crossing: New Horizons, 42.79
Nintendo, Super Smash Bros. Ultimate, 31.77
Nintendo, The Legend of Zelda: Breath of the Wild, 30.65
Nintendo, Super Mario Odyssey, 26.44
Nintendo, Pokemon Sword/Shield, 25.92
Nintendo, Pokemon Scarlet/Violet, 22.66
Nintendo, Super Mario Party, 19.39
Nintendo, The Legend of Zelda: Tears of the Kingdom, 18.51
Nintendo, New Super Marios Bros. U Deluxe, 17.17