%%{init: { 'logLevel': 'debug', 'theme': 'forest' } }%%
timeline
    title Java Version History
    1996: Java 1.0
        : Yahoo
    1997: Java 1.1
        : IBM's Deep Blue defeats a world chess champion
    1998: Java 1.2
        : Google
    2000: Java 1.3
        : Dot-com bubble burst
    2002: Java 1.4
        : Windows XP Release
    2004: Java 5.0
        : Facebook
    2006: Java 6
        : Twitter (Presently X)
    2011: Java 7
        : IBM's Watson won a game of Jeopardy!
    2014: Java 8
        : iPhone 6 & 6 Plus release
    2017: Java 9
        : SpaceX launched and reused a rocket 
    2018: Java 10
        : Java 11
        : General Data Protection Regulation implemented in EU.
    2019: Java 12
        : Java 13
        : First ever image of a black hole was released
    2020: Java 14
        : Java 15
        : Covid-19 pandemic (profound global impact)
    2021: Java 16
        : Java 17
        : Mars rover Perseverance successfully landed on Mars