pie
  "International business/trade/commerce" : 11
  "Political science and government" : 8.8
  "Psychology" : 7.2
  "Econometrics and quantitative economics" : 4.5
  "Economics" : 4.3
  "International relations and affairs" : 4.3
  "Biology/biological sciences" : 4
  "Neuroscience" : 3.8
  "English language and literature" : 3.7
  "Mathematics" : 3.5
  "Social and philosophical foundations of education" : 3.3
  "Biochemistry and molecular biology" : 3.3
  "Spanish language and literature" : 3
  "Public policy analysis" : 2.6
  "Environmental studies" : 2.4
  "Computer science" : 2.4
  "Environmental science" : 2.2