journey
    title My Dickinson Day
    section Attend Class
      Latin American History: 0: Me
      Spanish Creative Writing: 4.5: Me
      %% I'm just so happy to be in senior seminar
      CS Senior Seminar: 3, : Me, Mermaid
    section Dorm
      Doing homework: 3: Me
      Sleeping: 7: Me
    section Gaming Time
      Valorant: -10: Me
      Overwatch2: 2: Me
      Showdown: 4: Me
      Pokemon Go: 6: Me
      