gantt
    title My Day
    dateFormat  MM-DD-YYYY MM:HH
    section Morning
    Wakeup          :a1, 04-12-2023 08:00, 15m
    Get Dressed     :after a1  , 5m
    Eat Breakfast   : 30m
    Homework    : 1h
    Go to Class : 130m

    section Afternoon
    Eat Lunch     :04-12-2023 12:00 , 35m
    Nap      : 90m
    Work    : 130m
    Free Time   :   75m

    section Evening
    Eat Dinner  :04-12-2023 17:30, 45m
    Free Time   :   135m
    Homework   :04-12-2023 20:30, 150m
    Get Ready For Bed   :04-12-2023 23:00, 55m