journey
    title Customer Satisfaction
    section AM Shift
      Customer 1: 5: Worker 1
      Customer 2: 3: Worker 1
      Customer 3: 1: Worker 1
    section PM Shift
      Customer 4: 5: Worker 2
      Customer 5: 3: Worker 2
      Customer 6: 7: Worker 2