mindmap
  root((Computer))
    Storage
        Operating System
    I/O
        Mouse
        Keyboard
        Display
        Network
    MotherBoard
        CPU
        Memory
            RAM
            Cache
        Power Supply