quadrantChart
    title Risk vs Reward
    x-axis Low Risk --> High Risk
    y-axis Low Reward --> High Reward
    quadrant-1 Might Be Worth It
    quadrant-2 Definitely Worth It
    quadrant-3 Might Be Worth It
    quadrant-4 Definitely Not Worth It
    Pet a Raccoon: [0.87, 0.89]
    Bet Life Savings: [0.9, 0.05]
    Do Laundry: [0.30, 0.24]
    Bake Brownies: [0.35, 0.78]